name: Scan for secrets

on:
  pull_request:
  merge_group:
    types:
    - checks_requested

jobs:
  secret-scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - id: establish_metadata
        name: Establish event metadata
        shell: bash
        run: |
          # Based on https://github.com/trufflesecurity/trufflehog/blob/d7f4ec54889045fe3dac0c62d7ef10f5d130025e/README.md#shallow-cloning

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "fetch_depth=$((${{ github.event.pull_request.commits }} + 2))" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "merge_group" ]]; then
            # For merge group, we'll use a default depth since commit count isn't directly available
            echo "fetch_depth=50" >> $GITHUB_OUTPUT
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.establish_metadata.outputs.branch }}
          fetch-depth: ${{ steps.establish_metadata.outputs.fetch_depth }}

      - name: Run TruffleHog secret scan
        uses: trufflesecurity/trufflehog@939f053fc5cc13136efeb9e4d505051455d135dd  # v3.82.13
        with:
          extra_args: --only-verified
