
name: Semgrep
permissions: read-all
on:
  pull_request: {}
  push:
    branches:
    - initial-setup
  schedule:
    - cron: 28 3 1 * *
  workflow_dispatch: {}
jobs:
  semgrep:
    uses: gemini/semgrep/.github/workflows/semgrep-base.yml@main
    secrets: inherit
